---
layout: cv
title: Camden Stoker's Resume
---
# Camden J. Stoker
(509) 714-8210 

<div id="webaddress">
<a href="stokercamden@gmail.com">stokercamden@gmail.com</a>
| <a href="www.linkedin.com/in/camden-stoker-089384332">My Linkedin Page</a>
</div>


## Education
**Brigham Young University - Idaho** | Rexburg, ID
Bachelor of Data Science | Minor: Business Financial Analysis
[cite_start]September 2024 - Present [cite: 1, 2]

## Experience
### High Country Automotive
Warehouse Hand | Lewiston, ID | [cite_start]August 2024 - September 2024 [cite: 3]
* [cite_start]Automotive Parts delivery and supplier [cite: 3]
* [cite_start]Processed efficiently and managed online and phone orders, ensuring timely and accurate delivery, enhancing order times by 40%. [cite: 3, 4]
* [cite_start]Coordinated and reviewed order deliveries to maintain high-quality service, which in turn brought more customers to doors by 25%. [cite: 4, 5]
* [cite_start]Streamlined stock management processes, resulting in improved inventory accuracy by 60%. [cite: 5]
* [cite_start]Collaborated with customers to identify needs and recommend suitable products, enhancing customer satisfaction, allowing networking with local shops looking to grow business by over 50%. [cite: 6, 7]

### Church of Jesus Christ of Latter-Day Saints
Missionary | St. George, UT | [cite_start]August 2022 - August 2024 [cite: 8]
* [cite_start]Served the Spanish speaking people in area, taught lessons about the Gospel of Jesus Christ, helped people better lives through Jesus Christ. [cite: 8]
* [cite_start]Led with other people with same goals and intentions, headed some projects with Google Sheets and some programming specifically dealing with Python and sheet organization. [cite: 8]

## Awards
* Eagle Scout with Bronze Palm
* Colonel as Group Commander for Air Force JROTC

## Key Projects
### Clearview Project (Data Science Society)
Rexburg, ID | [cite_start]October 2024 - April 2025 [cite: 9]
* [cite_start]Built a database and will manage large amounts of data. [cite: 9]
* [cite_start]Leveraged database and connections through JavaScript to make a functional website. [cite: 9]
* [cite_start]Finished and presented project as a team member, using PostgreSQL, JavaScript, HTML. [cite: 9]

### Property Office Project (Data Science Society)
Rexburg, ID | [cite_start]October 2024 - Present [cite: 9]
* [cite_start]Built a database and will manage large amounts of data. [cite: 9]
* [cite_start]Cleansed the data and also went in starting insert statements. [cite: 9]


### Trail Restoration (Boy Scouts of America)
Lewiston, ID | [cite_start]September 2018 - February 2019 [cite: 10]
* [cite_start]Outlined plans of whole project, found sponsors for funds, obtained materials needed, spoke with community members in public meetings. [cite: 10]
* [cite_start]Arranged for help on specific days and times, planted and controlled seed planted for breeding ground. [cite: 10]
* [cite_start]Improved land by 80% and doubled breeding of animals. [cite: 11]


<!-- ### Footer

Last updated: May 2013 -->