name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write # Added: Necessary for modern GitHub Pages deployments
      id-token: write # Added: Necessary for modern GitHub Pages deployments (OIDC)
    environment: # Recommended for GitHub Pages environments
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # tinytex: true # Only needed if you plan to build PDFs within the Quarto site
          version: 'latest' # It's good practice to specify 'latest' or a specific version

      # Install Python and Dependencies
      - name: Install Python and Dependencies
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'
          cache: 'pip' # Enable caching for faster installs
      - name: Install Python packages
        run: pip install jupyter numpy pandas scikit-learn lets-plot palmerpenguins seaborn matplotlib plotly.express

      # If you need to render the *entire* Quarto project to HTML for GitHub Pages:
      - name: Render and Publish Quarto site to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          # The 'target-branch' or 'target' should be 'gh-pages' for GitHub Pages
          # The action will render the project and push to this branch
          target-branch: gh-pages
          # Optionally specify a base url if your site is in a subfolder on GH Pages
          # base-url: /your-repo-name/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is usually automatically available
